index:
    pattern: /
    defaults:  { _controller: UserBase\Server\Controller\SiteController::indexAction }

login:
    pattern: /login
    defaults:  { _controller: UserBase\Server\Controller\SiteController::loginAction }

login_submit:
    pattern: /login/submit
    defaults:  { _controller: UserBase\Server\Controller\SiteController::loginSubmitAction }

signup:
    pattern: /signup
    defaults:  { _controller: UserBase\Server\Controller\SiteController::signupAction }

signup_submit:
    pattern: /signup/submit
    defaults:  { _controller: UserBase\Server\Controller\SiteController::signupSubmitAction }

signup_thankyou:
    pattern: /signup/thankyou
    defaults:  { _controller: UserBase\Server\Controller\SiteController::signupThankYouAction }

cp_index:
    pattern: /cp
    defaults:  { _controller: UserBase\Server\Controller\CpController::indexAction }

api_v1_root:
    pattern: /api/v1
    defaults:  { _controller: UserBase\Server\Controller\ApiController::indexAction }


admin_index:
    pattern: /admin
    defaults:  { _controller: UserBase\Server\Controller\AdminController::indexAction }

admin_user_list:
    pattern: /admin/users
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userListAction }

admin_user_view:
    pattern: /admin/users/{username}
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userViewAction }
