index:
    path: /
    defaults:  { _controller: UserBase\Server\Controller\SiteController::indexAction }

login:
    path: /login
    defaults:  { _controller: UserBase\Server\Controller\SiteController::loginAction }

login/success:
    path: /login/success
    defaults:  { _controller: UserBase\Server\Controller\SiteController::loginSuccessAction }

logout/success:
    path: /logout/success
    defaults:  { _controller: UserBase\Server\Controller\SiteController::logoutSuccessAction }

signup:
    path: /signup
    defaults:  { _controller: UserBase\Server\Controller\SiteController::signupAction }

signup_submit:
    path: /signup/submit
    defaults:  { _controller: UserBase\Server\Controller\SiteController::signupSubmitAction }

signup_thankyou:
    path: /signup/thankyou
    defaults:  { _controller: UserBase\Server\Controller\SiteController::signupThankYouAction }

validate:
    path: /validate/{username}/{stamp}/{token}
    defaults:  { _controller: UserBase\Server\Controller\SiteController::validateAction }

validate_success:
    path: /validate/success
    defaults:  { _controller: UserBase\Server\Controller\SiteController::validateSuccessAction }

password_lost:
    path: /password/lost
    defaults:  { _controller: UserBase\Server\Controller\SiteController::passwordLostAction }

password_reset_request:
    path: /password/reset-request
    defaults:  { _controller: UserBase\Server\Controller\SiteController::passwordResetRequestAction }

password_reset:
    path: /password/reset/{username}/{stamp}/{token}
    defaults:  { _controller: UserBase\Server\Controller\SiteController::passwordResetAction }

password_reset_submit:
    path: /password/reset-submit/{username}/{stamp}/{token}
    defaults:  { _controller: UserBase\Server\Controller\SiteController::passwordResetSubmitAction }

password_reset_sent:
    path: /password/reset-sent
    defaults:  { _controller: UserBase\Server\Controller\SiteController::passwordResetSentAction }

password_reset_success:
    path: /password/reset-success
    defaults:  { _controller: UserBase\Server\Controller\SiteController::passwordResetSuccessAction }

cp_index:
    path: /cp
    defaults:  { _controller: UserBase\Server\Controller\CpController::indexAction }

cp_app_login:
    path: /cp/applogin/{appname}
    defaults:  { _controller: UserBase\Server\Controller\CpController::appLoginAction }

api_v1_root:
    path: /api/v1
    defaults:  { _controller: UserBase\Server\Controller\ApiController::indexAction }

api_v1_user_list:
    path: /api/v1/users
    defaults:  { _controller: UserBase\Server\Controller\ApiController::userListAction }
    
api_v1_user_view:
    path: /api/v1/users/{username}
    defaults:  { _controller: UserBase\Server\Controller\ApiController::userViewAction }







admin_index:
    path: /admin
    defaults:  { _controller: UserBase\Server\Controller\AdminController::indexAction }

admin_user_list:
    path: /admin/users
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userListAction }

admin_user_view:
    path: /admin/users/{username}
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userViewAction }

admin_user_tools:
    path: /admin/users/{username}/tools
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userToolsAction }

admin_user_update_password:
    path: /admin/users/{username}/updatepassword
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userUpdatePasswordAction }

admin_user_update_email:
    path: /admin/users/{username}/updateemail
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userUpdateEmailAction }

admin_user_update_displayname:
    path: /admin/users/{username}/updatedisplayname
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userUpdateDisplayNameAction }

admin_log_list:
    path: /admin/logs
    defaults:  { _controller: UserBase\Server\Controller\AdminController::logListAction }


admin_groups_list:
    path: /admin/groups
    defaults:  { _controller: UserBase\Server\Controller\AdminController::groupListAction }

admin_apps_list:
    path: /admin/apps
    defaults:  { _controller: UserBase\Server\Controller\AdminController::appListAction }
    
admin_app_view:
    path: /admin/apps/{appname}
    defaults:  { _controller: UserBase\Server\Controller\AdminController::appViewAction }
