index:
    pattern: /
    defaults:  { _controller: UserBase\Server\Controller\SiteController::indexAction }

login:
    pattern: /login
    defaults:  { _controller: UserBase\Server\Controller\SiteController::loginAction }

login/success:
    pattern: /login/success
    defaults:  { _controller: UserBase\Server\Controller\SiteController::loginSuccessAction }

logout/success:
    pattern: /logout/success
    defaults:  { _controller: UserBase\Server\Controller\SiteController::logoutSuccessAction }

signup:
    pattern: /signup
    defaults:  { _controller: UserBase\Server\Controller\SiteController::signupAction }

signup_submit:
    pattern: /signup/submit
    defaults:  { _controller: UserBase\Server\Controller\SiteController::signupSubmitAction }

signup_thankyou:
    pattern: /signup/thankyou
    defaults:  { _controller: UserBase\Server\Controller\SiteController::signupThankYouAction }

password_reset:
    pattern: /password/reset
    defaults:  { _controller: UserBase\Server\Controller\SiteController::passwordResetAction }


cp_index:
    pattern: /cp
    defaults:  { _controller: UserBase\Server\Controller\CpController::indexAction }

api_v1_root:
    pattern: /api/v1
    defaults:  { _controller: UserBase\Server\Controller\ApiController::indexAction }

api_v1_user_list:
    pattern: /api/v1/users
    defaults:  { _controller: UserBase\Server\Controller\ApiController::userListAction }
    
api_v1_user_view:
    pattern: /api/v1/users/{username}
    defaults:  { _controller: UserBase\Server\Controller\ApiController::userViewAction }


admin_index:
    pattern: /admin
    defaults:  { _controller: UserBase\Server\Controller\AdminController::indexAction }

admin_user_list:
    pattern: /admin/users
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userListAction }

admin_user_view:
    pattern: /admin/users/{username}
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userViewAction }

admin_user_tools:
    pattern: /admin/users/{username}/tools
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userToolsAction }

admin_user_update_password:
    pattern: /admin/users/{username}/updatepassword
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userUpdatePasswordAction }

admin_user_update_email:
    pattern: /admin/users/{username}/updateemail
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userUpdateEmailAction }

admin_user_update_displayname:
    pattern: /admin/users/{username}/updatedisplayname
    defaults:  { _controller: UserBase\Server\Controller\AdminController::userUpdateDisplayNameAction }

admin_log_list:
    pattern: /admin/logs
    defaults:  { _controller: UserBase\Server\Controller\AdminController::logListAction }
